### ISSUE TITLE
File Formidable

### ISSUE THREAD

**Issue by dungtm007** [sindresorhus/awesome-nodejs#1080]
Heard about this:

https://github.com/node-formidable/formidable'
_"A node.js module for parsing form data, especially file uploads."_

Don't see it it the list. Is it considerable good? Any similar in the list, instead?

Best Regards,
Tom

**Comment by sindresorhus** [comment]
See: https://github.com/sindresorhus/awesome-nodejs/issues/939#issuecomment-533908448

**Comment by sindresorhus** [comment]
I think this would be a good question for https://github.com/sindresorhus/awesome-nodejs/discussions?discussions_q=category%3AQ%26A "What form data package do people recommend?"
