### ISSUE TITLE
Question respect to in which section add a project

### ISSUE THREAD

**Issue by viferga** [sindresorhus/awesome-nodejs#1148]
Hi, I am developing a Polyglot Runtime called MetaCall ( https://github.com/metacall/core ). This is basically a library/tool that you can use from NodeJS in order to import libraries from other languages (it supports NodeJS, JavaScript, TypeScript, Python, Ruby, C#, Wasm, Java, Cobol and more).

Here's an example of importing BeautifulSoup (Python scrapping library) into NodeJS and using it: https://github.com/metacall/beautifulsoup-express-example

Here's the NPM package: https://www.npmjs.com/package/metacall

I would like to know where should I add this project, or if should I create a new section for it.
Thanks for your time.

**Comment by sindresorhus** [comment]
You can add it to `Miscellaneous` for now. I don't create new categories unless there are at least two items for it.
