### ISSUE TITLE
Kindly, verify and add Open-Listings if it fits the list

### ISSUE THREAD

**Issue by yanna92yar** [sindresorhus/awesome-nodejs#1244]
[Open-Listings](https://github.com/yanna92yar/open-listings) is an open listings complete web-app. It is multi-lingual and supports maps and tags.

Not the most sophisticated listings website, but it is probably the only one in NodeJS on GitHub

Thanks @sindresorhus .

**Comment by sindresorhus** [comment]
Thanks for the suggestion, but I'm not looking to add web apps to the list.
