### ISSUE TITLE
where should live help resources be added?

### ISSUE THREAD

**Issue by cmrnh** [sindresorhus/awesome-nodejs#305]
Hey @sindresorhus, what's the best place to add live help resources? (Happy to create a PR, just wanted to ask here before taking a wild guess.)

For example, I've been hosting open group hangouts with other node developers at Thinkful every day at 11am, and we want to get more people to attend — so we'd like to add it to the resource list somewhere. The [sign-up](http://start.thinkful.com/node/) serves to reserve one of the 10 spots (the max that Google Hangouts supports).

There's also Slack teams dedicated to Node [like this one](http://nodeslackers.io/), etc. that it might make sense to add.

Thoughts? Maybe it fits best under a "live help" subsection within [Resources](https://github.com/sindresorhus/awesome-nodejs#resources)

**Comment by sindresorhus** [comment]
I would say an `Events` sections within a new section called `Community`. ?

**Comment by cmrnh** [comment]
Awesome :) I'll take a stab at a PR and we can discuss there?
