### ISSUE TITLE
Sort categories alphabetically

### ISSUE THREAD

**Issue by simov** [sindresorhus/awesome-nodejs#348]
:wave: 

I think when you have so much categories it's better to sort them alphabetically. For example even if I know the category I'm looking for, I still can't find it without browser searching for it.

This applies to category entries as well.

**Comment by sindresorhus** [comment]
{Cmd,Ctrl}+F will be faster no matter if it's sorted or not. I prefer to have it sorted by interestingness.

**Comment by simov** [comment]
Ok, still {Cmd,Ctrl}+F will be faster only if you are searching for something specific, for occasional browsing alphabetical order would be better.

**Comment by sindresorhus** [comment]
You have a good point. I'm just not willing to sacrifice the usefulness of having the most interesting categories first. I want to make an automatically generated website for the list at some point and it would have sorting options.

**Comment by simov** [comment]
:+1: that makes sense
