### ISSUE TITLE
suggestion: URL section?

### ISSUE THREAD

**Issue by puzrin** [sindresorhus/awesome-nodejs#352]
There are some packages in [Text](https://github.com/sindresorhus/awesome-nodejs#text) section to work with URLs, but it's not evident for search. Also i could suggest 2 new:

- https://github.com/nodeca/url-unshort
- https://github.com/nodeca/embedza

and those are not ok for `Text` too. May be it's time to create `URL` section?

**Comment by sindresorhus** [comment]
:+1:
