### ISSUE TITLE
Table of contents?

### ISSUE THREAD

**Issue by Klortho** [sindresorhus/awesome-nodejs#457]
I see that's one of the recommendations [here](https://github.com/sindresorhus/awesome/blob/master/awesome.md). It would help with this list, I think!

**Comment by sindresorhus** [comment]
:+1: Wanna do a pull request?

**Comment by dthree** [comment]
https://github.com/sindresorhus/awesome-nodejs/pull/458

**Comment by Klortho** [comment]
Thanks!

**Comment by dthree** [comment]
:+1:
