### ISSUE TITLE
[Suggestion] Is it possible to add 'step-by-step' section ?

### ISSUE THREAD

**Issue by ghost** [sindresorhus/awesome-nodejs#488]
Anybody learning Node.js wants to go through steps from beginner to advanced level , so should you add **'step-by-step' section *_or something like *_timeline** to ease learning process ?

**Comment by sindresorhus** [comment]
Good idea! I think it would be better as a blog post that could be linked to, though.

**Comment by itsjtwright** [comment]
https://www.airpair.com/javascript/node-js-tutorial something like this? or a list of projects that are shown step by step?

**Comment by itsjtwright** [comment]
Issued a pr for a resource that should be able to answer your request
