### ISSUE TITLE
Please consider jsdom and nw.js

### ISSUE THREAD

**Issue by vsemozhetbyt** [sindresorhus/awesome-nodejs#494]
May be [jsdom](https://github.com/tmpvar/jsdom) and [nw.js](https://github.com/nwjs/nw.js) are also worth adding. They are fundamental enough and very popular.

**Comment by kevva** [comment]
As for `nw.js`, it has already been answered here https://github.com/sindresorhus/awesome-nodejs/pull/322. `jsdom` is pretty useful in testing though.

**Comment by vsemozhetbyt** [comment]
Oh, sorry for not searching first. Well, do consider jsdom then.

**Comment by sindresorhus** [comment]
Happy to add `jsdom`. Read the [contributing guidelines](../blob/master/contributing.md) and do a pull request adding it ;)
