### ISSUE TITLE
iCalendar VObject Manipulation in NodeJS

### ISSUE THREAD

**Issue by killmenot** [sindresorhus/awesome-nodejs#507]
Hi @sindresorhus 

I've found this great repo (https://github.com/outlook/vobject-js) recently but not sure what category is the best for it. By my mind it's good to be placed in `Email` section but I'd like to discuss it first. WDYT?

**Comment by sindresorhus** [comment]
I don't think this is general enough to be in the list. The list are for stuff most will need. If someone needs this specific thing, they can easily search for it ;)
