### ISSUE TITLE
[Suggestion] Mysqldump

### ISSUE THREAD

**Issue by webcaetano** [sindresorhus/awesome-nodejs#515]
Hello guys, i have this utility mysql module,
that make dump files .sql. 

Very good for backup purposes.
It are well documented and strongly tested on `travis`

I create this issue before make an PR because i have a question.
"Where i add it on the list?"
Should i create a sub-category on `databases` for * utilities ? 

https://github.com/webcaetano/mysqldump

**Comment by sindresorhus** [comment]
Thanks for the suggestion, but this is a bit too niche for the list.
