### ISSUE TITLE
(Sugestion) Consider add this project to list

### ISSUE THREAD

**Issue by pmcfernandes** [sindresorhus/awesome-nodejs#522]
Hi please consider add this project to your list. Is a boilerplate for express with support for passport and mongo pre configured 

https://github.com/Patreo/BoilerplateNodeJS

**Comment by sindresorhus** [comment]
Thanks for the suggestion, but I'm not adding boilerplates. There are a gadzillion different boilerplates and combinations and I really don't have time to review them all ;)
