### ISSUE TITLE
Competing awesome-nodejs repos

### ISSUE THREAD

**Issue by mcauser** [sindresorhus/awesome-nodejs#527]
Merge? collaborate?
https://github.com/sindresorhus/awesome-nodejs
https://github.com/vndmtrx/awesome-nodejs
Chinese translation:
https://github.com/ueqt/awesome-nodejs

https://github.com/vndmtrx/awesome-nodejs/issues/60

**Comment by sindresorhus** [comment]
I don't really see the point. That other one almost haven't been maintained the past two years.

**Comment by mcauser** [comment]
Sorry, I should have probably checked that first
