### ISSUE TITLE
Have a good "printing area" package?

### ISSUE THREAD

**Issue by thearabbit** [sindresorhus/awesome-nodejs#544]
I would like to print the report (via area/template) on `Meteor JS`.
Pleas help me.

**Comment by SamVerschueren** [comment]
What do you need? I believe this issue doesn't belong in this repository. You might consider moving it to https://github.com/sindresorhus/module-requests where you can request a module you wish existed.

**Comment by thearabbit** [comment]
Sorry, thanks.

**Comment by sindresorhus** [comment]
And please be a lot more descriptive if you're going to open an issue on `module-requests`.
