### ISSUE TITLE
[Suggestion] add Ajv to Data validation section

### ISSUE THREAD

**Issue by epoberezkin** [sindresorhus/awesome-nodejs#575]
[Ajv](https://github.com/epoberezkin/ajv) - the fastest JSON-schema validator

**Comment by sindresorhus** [comment]
Sure. Read https://github.com/sindresorhus/awesome-nodejs/blob/master/contributing.md and do a pull request ;)

**Comment by epoberezkin** [comment]
Thanks for confirming!
