### ISSUE TITLE
For emails

### ISSUE THREAD

**Issue by niftylettuce** [sindresorhus/awesome-nodejs#612]
For emails:

* https://github.com/crocodilejs/custom-fonts-in-emails
* https://github.com/crocodilejs/font-awesome-assets
* https://github.com/crocodilejs/node-email-templates
* https://github.com/nodemailer/nodemailer
* https://github.com/crocodilejs/nodemailer-base64-to-s3

**Comment by sindresorhus** [comment]
Nodemailer is already included. The others are not general enough. Next time please pick one.
