### ISSUE TITLE
Can I create a PR for `ws`?

### ISSUE THREAD

**Issue by plantain-00** [sindresorhus/awesome-nodejs#650]
https://github.com/websockets/ws

**Comment by sindresorhus** [comment]
Nah. Already have `uWS`, which is a lot faster.

https://github.com/sindresorhus/awesome-nodejs#real-time

**Comment by plantain-00** [comment]
I use uws for server-side websocket usage too.
but the client-side uws is worse than the client-side ws, so I use ws for cliend-side usage.
