### ISSUE TITLE
Why you place ads in the readme?

### ISSUE THREAD

**Issue by dkfiresky** [sindresorhus/awesome-nodejs#659]

**Comment by itsjtwright** [comment]
I was wondering the same thing

**Comment by sindresorhus** [comment]
It's not ads. It's one affiliate link to a course I would recommend regardless. I'm experimenting with monetizing open-source. Going to write a blog post at some point.

**Comment by dkfiresky** [comment]
@sindresorhus what is the difference between an affiliate link to a paid service vs a "general" ad?

**Comment by sindresorhus** [comment]
Affiliate links are usually more relevant because they're compensated based on actual referral sales, not clicks.

**Comment by dkfiresky** [comment]
@sindresorhus it's just the same ad but with a preference.
