### ISSUE TITLE
Add maintainers to increase the PR activity

### ISSUE THREAD

**Issue by StarpTech** [sindresorhus/awesome-nodejs#681]
Would be great when the review process could happens somewhat earlier. Some PR are 4 weeks old.

**Comment by sindresorhus** [comment]
This list is very much mature by now and it rarely gets any interesting submissions, so I review the PRs once in awhile in a batch. There's nothing time sensitive about them. If you want to help out. Ensure all the PRs follow the guidelines and help out the submitter if they don't.
