### ISSUE TITLE
[Addition] Node.js Based CCTV / NVR Software

### ISSUE THREAD

**Issue by moeiscool** [sindresorhus/awesome-nodejs#683]
Please add this to **Mad Science**

Shinobi - Open Source CCTV solution with both IP and local camera support.
**GPLv3**

**Source Code** : https://github.com/moeiscool/Shinobi
**Homepage** : http://shinobi.video
**Alternate Name** : ShinobiCCTV, NVRninja

**Comment by sindresorhus** [comment]
Looks like a cool project, but I wouldn't consider it "Mad Science". The GPLv3 license is also a big turn off.
