### ISSUE TITLE
Any awesome CLI REPL to recommend?

### ISSUE THREAD

**Issue by tleb** [sindresorhus/awesome-nodejs#701]
And therefore to add to the list. :+1:

**Comment by therealklanni** [comment]
In terminal, type `node`

**Comment by tleb** [comment]
Much thanks. I meant a proper REPL, such as `ptpython`.

**Comment by florianb** [comment]
Try [Mancy](https://github.com/princejwesley/Mancy). And since it is an electron app, it belongs to the awesome-electron list. 😃

**Comment by tleb** [comment]
Thanks @florianb, I have seen this, but I prefer CLI stuff. Is there really nothing? I'll give it a try though.

**Comment by florianb** [comment]
You're welcome - but i guess i don't understand what you're missing in the native node repl? It has f.e. tab-completion, colors everything a node developer needs. 😬

**Comment by therealklanni** [comment]
Not sure what you mean by "proper REPL", but running `node` is a _proper_ node REPL.

**Comment by ORESoftware** [comment]
@therealklanni a REPL repl :)

**Comment by Rudedog9d** [comment]
The only thing I wish the native `node` shell has is a better history, ex for when you define a function. Along the same lines, better multi-line editing.

I'm not sure a new shell is needed, maybe just an improvement to the native shell. @tleb what features do you feel the native shell is missing?

**Comment by tleb** [comment]
The features you mentioned and coloring on what we are writing, not just results, were mainly what I though about.

`ptpython` really is a great example of an amazing REPL as a CLI.

**Comment by Rudedog9d** [comment]
Agreed, syntax on the current command would be nice. I've used `ptpython`, and the builtin `node` CLI is already very close. You might try digging around [the node issue tracker](https://github.com/nodejs/node/issues?utf8=%E2%9C%93&q=label%3Arepl%20), they have a very active development community. The features you want might already be implemented, or you could implement it yourself :)
