### ISSUE TITLE
Add Total.js

### ISSUE THREAD

**Issue by Kingbalou** [sindresorhus/awesome-nodejs#707]
Under framework

https://www.totaljs.com

> Total.js is full-featured server-side framework which effectively improves the most important aspects of your project during its lifetime. Super fast development, extremely low maintenance costs, rock solid stability, incredible performance and easy scaling.

**Comment by sindresorhus** [comment]
https://github.com/sindresorhus/awesome-nodejs/pull/680#issuecomment-299787963
