### ISSUE TITLE
Missing Command line Utilities?

### ISSUE THREAD

**Issue by piotryordanov** [sindresorhus/awesome-nodejs#711]
I noticed that `vorpal`, `inquirer` are listed, but not [commander](https://github.com/tj/commander.js) or [args](https://github.com/leo/args).

Both are actually mentioned in inquirer's README, and `commander` is probably the oldest of them. I was thinking of making a PR, but felt it was wiser to first ask why they were left out!

**Comment by ORESoftware** [comment]
commander is a pos

**Comment by florianb** [comment]
Besides of `meow` and `minimist`, [`yargs`](https://github.com/yargs/yargs) has recently found entry into the list (and it receives a high npms score if this is something to consider). I guess it will be difficult to have them added.

**Comment by piotryordanov** [comment]
@ORESoftware What is `pos` ?
@florianb I was referring to [args](https://github.com/leo/args) not `yargs`.

Isn't this supposed to be a list of libraries, letting the user decide which one to chose?  I don't know which is good, but when I go on `vorpal` which is listed here, and i find there a reference to `commander`, it makes me wonder if this list is comprehensive, or if it is opiniated, especially when commander is the CLI utility that has the most number of stars!

I'm confused :P

**Comment by sindresorhus** [comment]
This list is opinionated, that's the point. Stars are not a very useful measure of quality, just popularity.

**Comment by piotryordanov** [comment]
Oh, good to know. Thx!

**Comment by ORESoftware** [comment]
@piotryordanov pos is a pejorative term, that is why I did not spell it out :)

**Comment by florianb** [comment]
Sorry @piotryordanov, it wasn't my intention to confuse you. I mentioned `yargs` since it plays in the same discipline is already added. It is getting harder to add a library with a functionality a listed library already provides. 😃

**Comment by piotryordanov** [comment]
@ORESoftware ah, I thought it meant `Point Of Serivice` xD
@florianb no worries, I got it :)
