### ISSUE TITLE
Any package for payment gateway?

### ISSUE THREAD

**Issue by apmeena** [sindresorhus/awesome-nodejs#717]
Please suggest all available options for online payment with Node.js.
Thanks.

**Comment by vpicone** [comment]
Wes Bos and Scott Tollinski covered this in their podcast this morning: you might want to have a listen

[Syntax.fm](https://syntax.fm)

**Comment by ofanidariyan** [comment]
still waiting for package of payment gateway 💯

**Comment by rajeeviiit** [comment]
please checkout this link for payment gateway hope it will help : https://www.npmjs.com/package/node-payments
