### ISSUE TITLE
Add an article about another ACL integration in Express API using CASL

### ISSUE THREAD

**Issue by stalniy** [sindresorhus/awesome-nodejs#752]
This is an article about authorization in Express with help of CASL - https://medium.com/netscape/authorization-with-casl-in-express-app-d94eb2e2b73b

There is also a full example on github - https://github.com/stalniy/casl-express-example

**Comment by sindresorhus** [comment]
Do a PR :)

https://github.com/sindresorhus/awesome-nodejs/blob/master/contributing.md
