### ISSUE TITLE
I wanna do PR, but don't know which category is suitable

### ISSUE THREAD

**Issue by samchon** [sindresorhus/awesome-nodejs#792]
What I want to insert to awesome list is the [TSTL](https://github.com/samchon/tstl) project, an implementation of C++ STL (Standard Template Library) in TypeScript. However, I don't know which category is suitable for that. Can you help me?

**Comment by sindresorhus** [comment]
That would be a better fit for https://github.com/sorrycc/awesome-javascript It's not specific to Node.js.
