### ISSUE TITLE
Awesomeness check for signale

### ISSUE THREAD

**Issue by novddd** [sindresorhus/awesome-nodejs#810]
Hi! I wondered if the signale node module is awesome anough for the list, saw it here: https://twitter.com/JavaScriptDaily/status/997106466875215873
github repository: https://github.com/klauscfhq/signale

Love  your work and the awesome list series! ❤️

**Comment by sindresorhus** [comment]
Good suggestion! Added: https://github.com/sindresorhus/awesome-nodejs/commit/6bc5dd15dae1fe3c1a93c566b45271fe55e81b42
