### ISSUE TITLE
[Suggestion] A few suggestions for a few Categories

### ISSUE THREAD

**Issue by Debdutto** [sindresorhus/awesome-nodejs#819]
Hi,

Just went through this amazing list. Found a few missing but amazing node libraries / frameworks / thingys that have made my node life a lot more amazing over the past years.

Please find the suggestions along with their probable categories below. I’m open to discuss and open a PR for each of them.

### Real-time
- aedes ([mcollina/aedes](https://github.com/mcollina/aedes)): From the creator of MQTT.js, it's a "Barebone MQTT broker that can run on any stream server, the node way".
Personally, I have used it on one of my production apps which is running for over 2 years.

### Weird
- xkcd ([grant/xkcd](https://github.com/grant/xkcd)): For people who love xkcd. This is an easy CLI / application tool to get your favourites.
I use this to get the latest one and send it over email to me. Start the day with a little xkcd and coffee. :)

### Process Management, or maybe Miscellaneous
- headrush ([gavindmello/headrush](https://github.com/GavinDmello/headrush)): A minimal solution to defer application start after resolving your network & processing dependancies.
I personally use this in one of our production apps to wait for node to connect to all required DBs and queues before starting the HTTP server and start accepting incoming requests.

### Audio (New section??), or maybe Miscellaneous
- MIDI.js ([mudcube/MIDI.js](https://github.com/mudcube/MIDI.js)): Making life easy to create a MIDI-app on the web. Includes a library to program synesthesia into your app for memory recognition or for creating trippy effects.
Never really used it that much (want to soon enough). But there are some wonderful usage examples on their readme, my favourite is [3d-Piano](https://www.borjamorales.com/3d-piano-player)

### Real-time, or maybe Miscellaneous
- monit-mqtt ([debdutto/monit-mqtt](https://github.com/Debdutto/monit-mqtt)): Made by yours truly. It's a small command line utility to monitor your mqtt broker's stats. A quick way to test if your broker is up, receiving messages and other stats.
I used it to monitor my raspberry pi broker's stats which I used to collect motion sensor data for one of my pet projects among others.

**Comment by sindresorhus** [comment]
> aedes (mcollina/aedes)

👍 PR welcome.

> xkcd (grant/xkcd)

👎 Would be a better fit for https://github.com/aharris88/awesome-cli-apps

> headrush (gavindmello/headrush)

👎 I don't really see the point of this module. You can easily do this with existing generic flow control libraries, or even just async/await:

```js
(async() => {
	await Promise.all([
		initialProcessing(),
		connectToMongo(),
		connectToRedis()
	]);

	console.log('ready');
})();
```

> MIDI.js (mudcube/MIDI.js):

👎 It's mainly for the web and not Node.js. Only the generator is Node.js and honestly too niche.

> monit-mqtt (debdutto/monit-mqtt)

👎 Looks too unfinished and unmaintained. The readme could use a lot of work and the version is 0.0.6. Also bit too niche for this list.
