### ISSUE TITLE
Debugging / Profiling recommendation - node-clinic

### ISSUE THREAD

**Issue by iSkore** [sindresorhus/awesome-nodejs#849]
I recommend adding [node-clinic](https://github.com/nearform/node-clinic) to the _Debugging / Profiling_ section of this collection.

In addition to being an excellent debugging and profiling tool, this project is maintained by [nearForm](https://www.nearform.com/) and has a few Node.js Core contributors working on it.

**Comment by sindresorhus** [comment]
Looks like a useful tool. PR welcome.
