### ISSUE TITLE
Awesomeness check for `fx` & `rels`

### ISSUE THREAD

**Issue by novdddd** [sindresorhus/awesome-nodejs#897]
Hi @sindresorhus! Lately i have been useing this two tools made with Node.js:

- https://github.com/klaussinani/rels
- https://github.com/antonmedv/fx

Do you think that anyone would be a worthy add to the list? If yes I can create a PR! Thank you a lot for your work!

**Comment by sindresorhus** [comment]
I think they would be a better fit for https://github.com/agarrharr/awesome-cli-apps
