### ISSUE TITLE
Add nvm?

### ISSUE THREAD

**Issue by sudo-suhas** [sindresorhus/awesome-nodejs#987]
I am aware that this isn't the first time this has come up but now that [`nvm` is an incubating project of the OpenJS Foundation](https://openjsf.org/blog/2019/10/03/openjs-foundation-welcomes-first-project-node-version-manager-nvm/), would you be willing to reconsider and add `nvm` to this curated list?

**Comment by sindresorhus** [comment]
Sorry, no. The problem was never who owned/maintained `nvm`, but rather its fundamental flaws, which are still there.

**Comment by sudo-suhas** [comment]
What you said reminded me of this:
> A decision can be both elegant for its time and short-sighted for the future. For example, see the recent crtique of Unix’s fork system call, “A fork() in the road,” by Andrew Baumann et al., from HotOS ’19. In fact, _nearly all designs end up being short-sighted given a long enough time scale_. We’d be fortunate for all our designs to last the 50 years that fork has. The most important part is to guard against short-term failures of vision, not very long-term ones. 

Source: https://research.swtch.com/proposals-representation

Please don't mistake this as an argument, just sharing something you might find interesting.
